name: env_bl_2026_JAMES
channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  - dask
  - netcdf4
  - jupyterlab
  - ipykernel
  - joblib

  - pip
  - pip:
      - xrft
      - xskillscore
      - jax
      - jaxlib
      - cmocean
      - jaxparrow
      - logging